# Generated by Django 5.1.1 on 2024-12-12 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_lattitude_order_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='medicines',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
